id: IB2AA35EF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:56:49+00:00'
last_modified: '2022-06-08T14:17:35.771300+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD89340
  title: བཀའ་ཐང་གསེར་ཕྲེང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AD53:
      image_group_id: I1PD89879
      title: ''
      total_pages: 726
      order: 1
      base_file: AD53.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
