id: IB2AA35EF
legacy_id: P010531
ocr_import_info:
  bdrc_scan_id: W1PD89340
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T08:52:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T05:18:56.237991+00:00'
last_modified: 2022-09-01 13:19:14.299415
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD89340
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1PD89340
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་ཐང་གསེར་ཕྲེང་།
  author: གཏེར་སྟོན་སངས་རྒྱས་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.548353970608091
  ocr_word_median_confidence_index: 0.5600000023841858
quality: null
bases:
  I1PD89879:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD89879
      total_pages: 726
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD89879.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.548353970608091
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
